export enum PathRoutes {
  HOME = '/',
  HOME_REVIEW = '#review',
  HOME_FEATURES = '#features',
  HOME_MORE = '#more',
  LOGIN = '/login',
  REGISTER = '/register',
  RESET_PASSWORD = '/reset/password',
  CHANGE_PASSWORD = '/change/password/:link',
  ACTIVATE = '/activate/:link',
  STORAGE = '/storage',
  STORAGE_MY_DRIVE = '/storage/my-drive',
  STORAGE_SHARED = '/storage/chared',
  STORAGE_RECENT = '/storage/recent',
  STORAGE_STARRED = '/storage/starred',
  STORAGE_TRASH = '/storage/trash',
}
